<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-E00FH6K0" failures="0" tests="5" name="sales_order.VerifyCalculationForItemsWithInclusivePPNisTicked" time="0.866" errors="1" timestamp="2022-12-08T14:18:20 ICT" skipped="0">
  <testcase classname="sales_order.VerifyCalculationForItemsWithInclusivePPNisTicked" name="firstTest" time="0.238"/>
  <system-out/>
  <testcase classname="sales_order.VerifyCalculationForItemsWithInclusivePPNisTicked" name="secondTest" time="0.245"/>
  <system-out/>
  <testcase classname="sales_order.VerifyCalculationForItemsWithInclusivePPNisTicked" name="thirdTest" time="0.100"/>
  <system-out/>
  <testcase classname="sales_order.VerifyCalculationForItemsWithInclusivePPNisTicked" name="fourthTest" time="0.217"/>
  <system-out/>
  <testcase classname="sales_order.VerifyCalculationForItemsWithInclusivePPNisTicked" name="fifthTest" time="0.066">
    <error message="Cannot format given Object as a Number" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Cannot format given Object as a Number
at java.base/java.text.DecimalFormat.format(DecimalFormat.java:518)
at java.base/java.text.Format.format(Format.java:158)
at sales_order.VerifyCalculationForItemsWithInclusivePPNisTicked.fifthTest(VerifyCalculationForItemsWithInclusivePPNisTicked.java:181)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- fifthTest -->
  <system-out/>
</testsuite> <!-- sales_order.VerifyCalculationForItemsWithInclusivePPNisTicked -->
